<a href="https://colab.research.google.com/github/akatjizeu/Data-Science/blob/main/hackathon/hackathon2/hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Load the google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Load test and train data from google drive
train_data = pd.read_csv('/content/drive/MyDrive/ML_DATASETS/ML_2/Train_set.csv')
test_data = pd.read_csv('/content/drive/MyDrive/ML_DATASETS/ML_2/Test_set.csv')
#

In [4]:
# Create a copy of the test data
train_data_copy = train_data.copy()

In [5]:
# View the first and last 5 rows of the train data copy
train_data_copy.head()

,ID,loan_amnt,loan_term,interest_rate,loan_grade,loan_subgrade,job_experience,home_ownership,annual_income,income_verification_status,...,delinq_2yrs,public_records,revolving_balance,total_acc,interest_receive,application_type,last_week_pay,total_current_balance,total_revolving_limit,default
0,72199369,9000,3 years,9.17,B,B2,<5 Years,OWN,85000.0,Not Verified,...,0.0,0.0,39519,20.0,59.60,INDIVIDUAL,4.0,95493.0,84100.0,0
1,14257956,18000,3 years,13.65,C,C1,<5 Years,OWN,64000.0,Verified,...,0.0,1.0,9783,24.0,3348.25,INDIVIDUAL,95.0,185433.0,13500.0,0
2,66216451,16000,3 years,7.26,A,A4,<5 Years,MORTGAGE,150000.0,Source Verified,...,2.0,0.0,13641,27.0,276.69,INDIVIDUAL,13.0,180519.0,19300.0,0
3,46974169,25000,3 years,13.99,C,C4,NaN,MORTGAGE,59800.0,Verified,...,0.0,0.0,35020,35.0,1106.72,INDIVIDUAL,17.0,183208.0,55400.0,0
4,46725961,17000,3 years,6.39,A,A2,10+ years,MORTGAGE,72000.0,Source Verified,...,0.0,0.0,23990,26.0,725.29,INDIVIDUAL,39.0,23990.0,81300.0,0

In [11]:
train_data_copy.tail()

,ID,loan_amnt,loan_term,interest_rate,loan_grade,loan_subgrade,job_experience,home_ownership,annual_income,income_verification_status,...,delinq_2yrs,public_records,revolving_balance,total_acc,interest_receive,application_type,last_week_pay,total_current_balance,total_revolving_limit,default
93169,65577252,3200,3 years,7.26,A,A4,<5 Years,RENT,85000.0,Not Verified,...,0.0,0.0,7924,38.0,55.34,INDIVIDUAL,13.0,64635.0,47600.0,0
93170,836021,3500,3 years,5.42,A,A1,NaN,MORTGAGE,57550.0,Not Verified,...,0.0,0.0,10174,24.0,299.67,INDIVIDUAL,161.0,NaN,NaN,1
93171,33058720,8000,3 years,13.98,C,C3,10+ years,RENT,148531.5,Source Verified,...,1.0,0.0,5391,25.0,1150.58,INDIVIDUAL,65.0,94596.0,6500.0,0
93172,4060472,35000,3 years,17.77,D,D1,<5 Years,RENT,100000.0,Verified,...,0.0,0.0,24609,45.0,5764.58,INDIVIDUAL,56.0,33759.0,34900.0,1
93173,3628127,10000,3 years,15.80,C,C3,<5 Years,RENT,60000.0,Verified,...,0.0,0.0,11285,7.0,2279.36,INDIVIDUAL,104.0,25594.0,12300.0,0

In [7]:
train_data_copy.shape

(93174, 23)

In [8]:
train_data_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93174 entries, 0 to 93173
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          93174 non-null  int64
 1   loan_amnt                   93174 non-null  int64
 2   loan_term                   93174 non-null  object
 3   interest_rate               93174 non-null  float64
 4   loan_grade                  93174 non-null  object
 5   loan_subgrade               93174 non-null  object
 6   job_experience              88472 non-null  object
 7   home_ownership              93174 non-null  object
 8   annual_income               93173 non-null  float64
 9   income_verification_status  93174 non-null  object
 10  loan_purpose                93174 non-null  object
 11  state_code                  93174 non-null  object
 12  debt_to_income              93174 non-null  float64
 13  delinq_2yrs                 93172 non-null  float64
 14  public_records              93172 non-null  float64
 15  revolving_balance           93174 non-null  int64
 16  total_acc                   93172 non-null  float64
 17  interest_receive            93174 non-null  float64
 18  application_type            93174 non-null  object
 19  last_week_pay               91250 non-null  float64
 20  total_current_balance       85788 non-null  float64
 21  total_revolving_limit       85788 non-null  float64
 22  default                     93174 non-null  int64
dtypes: float64(10), int64(4), object(9)
memory usage: 16.3+ MB

In [10]:
train_data_copy.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,93174.0,3.505021e+07,2.414926e+07,70735.00,10859832.50,3.710751e+07,5.859895e+07,73519746.00
loan_amnt,93174.0,1.473386e+04,8.428185e+03,500.00,8000.00,1.300000e+04,2.000000e+04,35000.00
interest_rate,93174.0,1.323343e+01,4.368728e+00,5.32,9.99,1.299000e+01,1.620000e+01,28.99
annual_income,93173.0,7.502826e+04,6.945478e+04,1200.00,45000.00,6.400000e+04,9.000000e+04,9500000.00
debt_to_income,93174.0,1.812762e+01,8.563084e+00,0.00,11.93,1.764000e+01,2.389000e+01,672.52
delinq_2yrs,93172.0,3.169944e-01,8.808591e-01,0.00,0.00,0.000000e+00,0.000000e+00,22.00
public_records,93172.0,1.961212e-01,5.811882e-01,0.00,0.00,0.000000e+00,0.000000e+00,49.00
revolving_balance,93174.0,1.685447e+04,2.368907e+04,0.00,6433.00,1.185600e+04,2.074500e+04,2560703.00
total_acc,93172.0,2.524891e+01,1.185506e+01,1.00,17.00,2.400000e+01,3.200000e+01,119.00
interest_receive,93174.0,1.747264e+03,2.088236e+03,0.00,439.88,1.070755e+03,2.219613e+03,23172.31
last_week_pay,91250.0,5.815488e+01,4.432656e+01,0.00,22.00,4.800000e+01,8.300000e+01,291.00
total_current_balance,85788.0,1.392529e+05,1.576868e+05,0.00,29642.00,7.936350e+04,2.071600e+05,8000078.00
total_revolving_limit,85788.0,3.208590e+04,4.705251e+04,0.00,14000.00,2.370000e+04,3.970000e+04,9999999.00
default,93174.0,2.375019e-01,4.255546e-01,0.00,0.00,0.000000e+00,0.000000e+00,1.00