<a href="https://colab.research.google.com/github/akatjizeu/Data-Science/blob/main/hackathon/hackathon1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd

# Load the dataset to check its structure and understand the features
file_path = '/content/Train_dataset.csv'
train = pd.read_csv(file_path)

#Load the test dataset
file_path = '/content/Test_dataset.csv'
test = pd.read_csv(file_path)

# Display the first few rows of the dataset
train.head()

,Registration Number,Annual Turnover,Cuisine,City,Restaurant Location,Opening Day of Restaurant,Facebook Popularity Quotient,Endorsed By,Instagram Popularity Quotient,Fire Audit,...,Overall Restaurant Rating,Live Music Rating,Comedy Gigs Rating,Value Deals Rating,Live Sports Rating,Ambience,Lively,Service,Comfortablility,Privacy
0,60001,42000000,"indian,irish",Bangalore,Near Business Hub,14-02-2009,84.3,Not Specific,95.8,1,...,10.0,4.0,NaN,NaN,NaN,8.0,8,6,6,6
1,60002,50000000,"indian,irish",Indore,Near Party Hub,29-09-2008,85.4,Tier A Celebrity,85.0,1,...,9.0,NaN,4.0,NaN,NaN,5.0,7,7,3,8
2,60003,32500000,"tibetan,italian",Chennai,Near Business Hub,30-07-2011,85.0,Tier A Celebrity,68.2,1,...,8.0,3.0,NaN,NaN,NaN,7.0,10,5,2,8
3,60004,110000000,"turkish,nigerian",Gurgaon,Near Party Hub,30-11-2008,85.6,Tier A Celebrity,83.6,0,...,9.0,6.0,NaN,NaN,NaN,7.0,7,4,3,5
4,60005,20000000,"irish,belgian",Manesar,Near Party Hub,22-02-2010,NaN,Tier A Celebrity,76.8,1,...,6.0,NaN,2.0,NaN,NaN,NaN,6,2,4,6

In [23]:
test.head()

,Registration Number,Cuisine,City,Restaurant Location,Opening Day of Restaurant,Facebook Popularity Quotient,Endoresed By,Instagram Popularity Quotient,Fire Audit,Liquor License Obtained,...,Overall Restaurant Rating,Live Music Rating,Comedy Gigs Rating,Value Deals Rating,Live Sports Rating,Ambience,Lively,Service,Comfortablility,Privacy
0,20001,"tibetan,italian",Bangalore,Near Business Hub,13-07-2010,78.00,Tier A Celebrity,69.00,1,1,...,6.0,NaN,2.0,NaN,NaN,5,2,2,6,0
1,20002,"tibetan,italian",Hyderabad,Near Party Hub,05-09-2011,89.17,Not Specific,96.00,1,1,...,9.0,3.0,NaN,NaN,6.0,7,8,5,1,8
2,20003,"algerian,belgian",Hyderabad,Near Party Hub,12-04-2011,84.00,Not Specific,86.00,1,1,...,6.0,3.0,NaN,NaN,NaN,9,7,5,1,5
3,20004,"tibetan,greek",-1,Near Party Hub,16-01-2005,79.38,Not Specific,74.40,0,1,...,9.0,6.0,NaN,NaN,NaN,6,7,6,4,7
4,20005,"cuban,british",Pune,Near Party Hub,10-11-2008,84.67,Not Specific,86.46,1,1,...,NaN,NaN,NaN,NaN,NaN,4,4,7,7,3

In [19]:
# Step 1: Check for missing values
missing_values = train.isnull().sum()

# Step 2: Convert date field into useful numerical features
train['Opening Day of Restaurant'] = pd.to_datetime(train['Opening Day of Restaurant'], format='%d-%m-%Y')
train['Years Since Opening'] = 2024 - train['Opening Day of Restaurant'].dt.year

# Step 3: Encode categorical variables
categorical_cols = ['Cuisine', 'City', 'Restaurant Location', 'Endorsed By']

# One-hot encode these columns
train_encoded = pd.get_dummies(train, columns=categorical_cols, drop_first=True)

# Drop unnecessary columns like 'Registration Number' and 'Opening Day of Restaurant' to avoid irrelevant features
train_encoded = train_encoded.drop(['Registration Number', 'Opening Day of Restaurant'], axis=1)

# Step 4: Fill missing values with median for numerical features
# Get a list of numerical columns
numerical_cols = train_encoded.select_dtypes(include=['number']).columns

# Fill missing values only in numerical columns with their median
train_encoded[numerical_cols] = train_encoded[numerical_cols].fillna(train_encoded[numerical_cols].median())

# Step 5: Scale numerical features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_features = scaler.fit_transform(train_encoded[numerical_cols]) # Scale only numerical features

# Create a trainFrame with scaled numerical features
scaled_train = pd.DataFrame(scaled_features, columns=numerical_cols, index=train_encoded.index)

# Concatenate scaled numerical features with the remaining columns of data_encoded
train_processed = pd.concat([train_encoded.drop(columns=numerical_cols), scaled_train], axis=1)

# Display the processed dataset ready for regression modeling
train_processed.head()

,Restaurant Type,Restaurant Theme,"Cuisine_algerian,belgian","Cuisine_algerian,korean","Cuisine_british,belgian","Cuisine_british,japanese","Cuisine_chinese,salvadorian","Cuisine_cuban,british","Cuisine_hawaiian,latvian","Cuisine_indian,irish",...,Live Music Rating,Comedy Gigs Rating,Value Deals Rating,Live Sports Rating,Ambience,Lively,Service,Comfortablility,Privacy,Years Since Opening
0,Bar,Arabian,False,False,False,False,False,False,False,True,...,-0.011238,0.042050,0.160521,0.100505,0.769892,0.609198,0.774295,1.389366,-0.145199,0.227711
1,Bar,Greek,False,False,False,False,False,False,False,True,...,-0.011238,2.202042,0.160521,0.100505,-0.698564,0.067740,1.307118,-0.116080,0.910329,0.790625
2,Bar,90's,False,False,False,False,False,False,False,False,...,-1.132841,0.042050,0.160521,0.100505,0.280407,1.692113,0.241471,-0.617895,0.910329,-0.898115
3,Bar,Arabian,False,False,False,False,False,False,False,False,...,2.231966,0.042050,0.160521,0.100505,0.280407,0.067740,-0.291352,-0.116080,-0.672964,0.790625
4,Bar,Greek,False,False,False,False,False,False,False,False,...,-0.011238,-2.117943,0.160521,0.100505,0.280407,-0.473717,-1.356999,0.385736,-0.145199,-0.335202

In [20]:
# Check the data types of all columns to identify non-numeric ones that might cause issues during scaling
train_encoded.dtypes

Annual Turnover                         int64
Facebook Popularity Quotient          float64
Instagram Popularity Quotient         float64
Fire Audit                              int64
Liquor License Obtained                 int64
                                       ...
City_vizag                               bool
City_vsakhapttnam                        bool
Restaurant Location_Near Party Hub       bool
Endorsed By_Not Specific                 bool
Endorsed By_Tier A Celebrity             bool
Length: 347, dtype: object

In [21]:
#train dat using lasso regression
#train dat using lasso regression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [26]:
# Assuming 'train' is your training dataset and 'test' is your test dataset
# Step 1: Check for missing values
missing_values = train.isnull().sum()

# Step 2: Convert date field into useful numerical features
train['Opening Day of Restaurant'] = pd.to_datetime(train['Opening Day of Restaurant'], format='%d-%m-%Y')
train['Years Since Opening'] = 2024 - train['Opening Day of Restaurant'].dt.year

# Step 3: Encode categorical variables
categorical_cols = ['Cuisine', 'City', 'Restaurant Location', 'Endorsed By']

# ----> Modified section starts here <----
# Create a function to split comma-separated values into multiple columns
def split_and_encode(df, column):
    # Split the comma-separated values in the column
    split_values = df[column].str.split(',', expand=True)

    # Create new column names for each split value
    new_cols = [f"{column}_{value}" for value in split_values.stack().unique()]

    # One-hot encode the split values
    encoded_values = pd.get_dummies(split_values.stack()).groupby(level=0).sum()  # Sum to handle duplicates
    encoded_values.columns = new_cols

    # Concatenate the encoded values with the original DataFrame
    df = pd.concat([df, encoded_values], axis=1)

    # Drop the original column
    df = df.drop(columns=[column])

    return df

# Apply the function to the 'Cuisine' column
train_encoded = split_and_encode(train, 'Cuisine')

# One-hot encode the other categorical columns
train_encoded = pd.get_dummies(train_encoded, columns=[col for col in categorical_cols if col != 'Cuisine'], drop_first=True)
# ----> Modified section ends here <----

# Drop unnecessary columns like 'Registration Number' and 'Opening Day of Restaurant' to avoid irrelevant features
train_encoded = train_encoded.drop(['Registration Number', 'Opening Day of Restaurant'], axis=1)

# Step 4: Fill missing values with median for numerical features
# Get a list of numerical columns
numerical_cols = train_encoded.select_dtypes(include=['number']).columns

# Fill missing values only in numerical columns with their median
train_encoded[numerical_cols] = train_encoded[numerical_cols].fillna(train_encoded[numerical_cols].median())

# Step 5: Scale numerical features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_features = scaler.fit_transform(train_encoded[numerical_cols]) # Scale only numerical features

# Create a trainFrame with scaled numerical features
scaled_train = pd.DataFrame(scaled_features, columns=numerical_cols, index=train_encoded.index)

# Concatenate scaled numerical features with the remaining columns of data_encoded
train_processed = pd.concat([train_encoded.drop(columns=numerical_cols), scaled_train], axis=1)

#

In [27]:
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import numpy as np

# Assuming 'train' is your training dataset and 'test' is your test dataset
# Separate features and target variable in the train and test datasets
X_train = train.drop('Annual Turnover', axis=1)  # Training features
y_train = train['Annual Turnover']               # Training target

X_test = test   # Testing features
y_test = test['Instagram Popularity Quotient']                 # Testing target

# Step 2: Preprocessing (Scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 3: Lasso Regression
lasso = Lasso(alpha=0.01)  # You can tune alpha via GridSearch
lasso.fit(X_train_scaled, y_train)

# Predict on test set
y_pred_lasso = lasso.predict(X_test_scaled)

# Calculate RMSE for Lasso
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred_lasso))
print(f"Lasso Regression RMSE: {rmse_lasso}")

# Step 4: Random Forest Regression
rf = RandomForestRegressor(n_estimators=200, max_depth=20, random_state=42)  # You can tune these hyperparameters
rf.fit(X_train, y_train)

# Predict on test set
y_pred_rf = rf.predict(X_test)

# Calculate RMSE for Random Forest
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
print(f"Random Forest RMSE: {rmse_rf}")

ValueError: could not convert string to float: 'indian,irish'

In [12]:
# Assuming your processed dataset is named 'data_encoded'
X = data_encoded.drop('Annual Turnover', axis=1)  # Features
y = data_encoded['Annual Turnover']               # Target

# ----> Identify and convert object (string) type columns to numerical
for col in X.select_dtypes(include=['object']).columns:
    try:
        X[col] = pd.to_numeric(X[col]) # Attempt direct conversion to numeric
    except ValueError:
        # If direct conversion fails, handle it (e.g., using one-hot encoding)
        print(f"Column '{col}' could not be directly converted to numeric. Applying one-hot encoding.")
        X = pd.get_dummies(X, columns=[col], drop_first=True, dummy_na=False) # Use dummy_na=False to avoid creating extra NaNs
# <----

# Split the data into training and test sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize Lasso regression
lasso = Lasso()

# Hyperparameter tuning using GridSearchCV
params = {'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}
lasso_cv = GridSearchCV(lasso, params, cv=5)

# Fit the model
lasso_cv.fit(X_train_scaled, y_train)

# Predict and evaluate
y_pred = lasso_cv.predict(X_test_scaled)
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"Best alpha for Lasso: {lasso_cv.best_params_['alpha']}")
print(f"Lasso Regression RMSE: {rmse_lasso}")

Column 'Restaurant Type' could not be directly converted to numeric. Applying one-hot encoding.
Column 'Restaurant Theme' could not be directly converted to numeric. Applying one-hot encoding.
Best alpha for Lasso: 100
Lasso Regression RMSE: 19410438.936902713

In [14]:


# Initialize Random Forest
rf = RandomForestRegressor(random_state=42)

# Hyperparameter tuning for Random Forest using GridSearchCV
params_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}
rf_cv = GridSearchCV(rf, params_rf, cv=5)

# Fit the model
rf_cv.fit(X_train, y_train)

# Predict and evaluate
y_pred_rf = rf_cv.predict(X_test)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print(f"Best parameters for Random Forest: {rf_cv.best_params_}")
print(f"Random Forest RMSE: {rmse_rf}")

Best parameters for Random Forest: {'max_depth': 20, 'min_samples_split': 10, 'n_estimators': 100}
Random Forest RMSE: 19705730.69727548